import {
  View, Text, StyleSheet, SafeAreaView, StatusBar,
  TouchableOpacity, ScrollView, Alert,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Feather } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';

export default function PDFPreviewScreen() {
  const navigation = useNavigation<any>();

  const handleDownload = () => {
    Alert.alert('Report Downloaded', 'Your health report has been saved to your files.');
  };

  const handleSendToDentist = () => {
    Alert.alert(
      'Send to Dentist',
      'This feature is coming soon. Your dentist will receive your report directly.',
      [{ text: 'OK' }]
    );
  };

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="light-content" />
      <LinearGradient colors={['#0a0f1e', '#0d1f3c']} style={styles.gradient}>

        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()}>
            <Feather name="arrow-left" size={24} color="rgba(255,255,255,0.7)" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Health Report</Text>
          <View style={{ width: 24 }} />
        </View>

        <ScrollView showsVerticalScrollIndicator={false}>
          {/* PDF Preview Card */}
          <View style={styles.previewCard}>
            {/* Report Header */}
            <View style={styles.reportHeader}>
              <View style={styles.reportLogo}>
                <Feather name="activity" size={18} color="#00c2ff" />
              </View>
              <View>
                <Text style={styles.reportAppName}>MouthWatch</Text>
                <Text style={styles.reportDate}>Generated Feb 21, 2026</Text>
              </View>
            </View>

            <View style={styles.divider} />

            {/* Patient Summary */}
            <Text style={styles.sectionLabel}>SCREENING SUMMARY</Text>
            <View style={styles.summaryRow}>
              <Text style={styles.summaryKey}>Latest Risk Level</Text>
              <View style={styles.redBadge}>
                <Text style={styles.redBadgeText}>High Risk</Text>
              </View>
            </View>
            <View style={styles.summaryRow}>
              <Text style={styles.summaryKey}>Combined Score</Text>
              <Text style={styles.summaryValue}>67.6 / 100</Text>
            </View>
            <View style={styles.summaryRow}>
              <Text style={styles.summaryKey}>Scans Completed</Text>
              <Text style={styles.summaryValue}>3</Text>
            </View>
            <View style={styles.summaryRow}>
              <Text style={styles.summaryKey}>Trend</Text>
              <Text style={[styles.summaryValue, { color: '#ff1744' }]}>Increasing ↑</Text>
            </View>

            <View style={styles.divider} />

            {/* Risk Factors */}
            <Text style={styles.sectionLabel}>REPORTED RISK FACTORS</Text>
            <View style={styles.riskFactorRow}>
              <Feather name="alert-circle" size={14} color="#ff1744" />
              <Text style={styles.riskFactorText}>Daily tobacco use</Text>
            </View>
            <View style={styles.riskFactorRow}>
              <Feather name="alert-circle" size={14} color="#ffea00" />
              <Text style={styles.riskFactorText}>Occasional alcohol consumption</Text>
            </View>

            <View style={styles.divider} />

            {/* Recommendation */}
            <Text style={styles.sectionLabel}>RECOMMENDATION</Text>
            <Text style={styles.recommendation}>
              Based on your screening results and reported risk factors, MouthWatch recommends seeking dental attention as soon as possible. Please bring this report to your appointment.
            </Text>

            <View style={styles.divider} />

            <Text style={styles.disclaimer}>
              This report is generated by MouthWatch and is intended as a screening aid only. It does not constitute a medical diagnosis. Always consult a qualified dental professional.
            </Text>
          </View>

          {/* Action Buttons */}
          <TouchableOpacity
            style={styles.primaryButton}
            onPress={handleDownload}
            activeOpacity={0.85}
          >
            <LinearGradient
              colors={['#00c2ff', '#0072ff']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 0 }}
              style={styles.primaryButtonGradient}
            >
              <Feather name="download" size={18} color="#fff" />
              <Text style={styles.primaryButtonText}>  Download PDF</Text>
            </LinearGradient>
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.secondaryButton}
            onPress={handleSendToDentist}
            activeOpacity={0.8}
          >
            <Feather name="send" size={18} color="#00c2ff" />
            <Text style={styles.secondaryButtonText}>  Send to My Dentist</Text>
          </TouchableOpacity>

          <View style={{ height: 32 }} />
        </ScrollView>
      </LinearGradient>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0a0f1e' },
  gradient: { flex: 1, paddingHorizontal: 24, paddingTop: 16 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  headerTitle: { fontSize: 17, fontWeight: '700', color: '#ffffff' },
  previewCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    marginBottom: 20,
    gap: 14,
  },
  reportHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  reportLogo: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,194,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(0,194,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportAppName: { fontSize: 16, fontWeight: '800', color: '#ffffff' },
  reportDate: { fontSize: 12, color: 'rgba(255,255,255,0.4)', marginTop: 2 },
  divider: { height: 1, backgroundColor: 'rgba(255,255,255,0.07)' },
  sectionLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.3)',
    letterSpacing: 1.5,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryKey: { fontSize: 14, color: 'rgba(255,255,255,0.5)' },
  summaryValue: { fontSize: 14, color: '#ffffff', fontWeight: '600' },
  redBadge: {
    backgroundColor: 'rgba(255,23,68,0.15)',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.3)',
  },
  redBadgeText: { fontSize: 12, fontWeight: '700', color: '#ff1744' },
  riskFactorRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  riskFactorText: { fontSize: 14, color: 'rgba(255,255,255,0.6)' },
  recommendation: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.6)',
    lineHeight: 21,
  },
  disclaimer: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.25)',
    lineHeight: 16,
  },
  primaryButton: { borderRadius: 16, overflow: 'hidden', marginBottom: 12 },
  primaryButtonGradient: {
    paddingVertical: 18,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  primaryButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,194,255,0.08)',
    borderRadius: 16,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: 'rgba(0,194,255,0.2)',
  },
  secondaryButtonText: { color: '#00c2ff', fontSize: 16, fontWeight: '600' },
});